# Generated by Django 4.2.6 on 2023-10-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bioText',
            field=models.TextField(default='Enter your bio', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fName',
            field=models.CharField(default='Rex', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lName',
            field=models.CharField(default='alem', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, default='images/users/default.jpg', null=True, upload_to='images/users'),
        ),
    ]
