# Generated by Django 4.2.7 on 2023-11-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration_app", "0007_authtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authtoken",
            name="ip_address",
            field=models.CharField(default="0.0.0.0", max_length=100),
        ),
    ]
