# Generated by Django 4.2.7 on 2023-11-18 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration_app", "0011_authtoken_digest_alter_authtoken_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authtoken",
            old_name="digest",
            new_name="hash",
        ),
    ]
