# Generated by Django 4.2.6 on 2023-10-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userRegister',
        ),
    ]
