# Generated by Django 4.2.6 on 2023-10-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_profile_biotext_profile_fname_profile_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, default='images/users/default.jpg', null=True, upload_to='media/users'),
        ),
    ]
