# Generated by Django 4.2.7 on 2023-11-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration_app", "0005_alter_profile_auth_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profilePic",
            new_name="profile_pic",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="auth_token",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bioText",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="fName",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="lName",
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
