# Generated by Django 4.2.7 on 2023-11-18 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("registration_app", "0009_alter_authtoken_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authtoken",
            options={},
        ),
        migrations.RemoveField(
            model_name="authtoken",
            name="created",
        ),
        migrations.AddField(
            model_name="authtoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="authtoken",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="authtoken",
            name="key",
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
