# Generated by Django 4.2.7 on 2023-11-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registration_app",
            "0010_alter_authtoken_options_remove_authtoken_created_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="authtoken",
            name="digest",
            field=models.CharField(
                default="7149b4f015aca69db020a5ad460aec0fb4ad48576b5396d4a9995d0e102975d07e71cdfba7687696f057ac1f5c9bc731bed9cbc768032ec5db3a8e819b0ed5e8",
                max_length=128,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="authtoken",
            name="key",
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
