# Generated by Django 4.2.7 on 2023-11-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration_app", "0012_rename_digest_authtoken_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authtoken",
            name="key",
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
