# Generated by Django 4.2.6 on 2023-10-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('website', 'WEBSITE'), ('game', 'GAME'), ('software', 'SOFTWARE'), ('mobile app', 'MOBILE APP'), ('other', 'OTHER')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='max_contributors',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
